name: CI pipeline

on:
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            pip install -r requirements.txt

        - name: Linting
          run: |    
            flake8 . --count --select=E9,F63,F7,F82 --show-source
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  

        - name: Test
          run: pytest -v

        - name: Ozgur
          run: |
            touch osman.txt
            echo "Ozgur is a great guy" > osman.txt
 
        - name: Archive production artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-without-markdown
            path: osman.txt